export type Item = {slug:string;name:string;latin:string;family:string;note:string;uses:string[];review:string};
export const products: Item[] = [
 {slug:'peppermint-oil',name:'Peppermint oil',latin:'Mentha piperita',family:'Natural oils',note:'A recognisable peppermint profile for sensory and analytical qualification.',uses:['Flavours & fragrances','Confectionery','Oral care'],review:'Confirm available grades, analytical range, pack and certification.'},
 {slug:'cornmint-oil',name:'Cornmint oil',latin:'Mentha arvensis',family:'Natural oils',note:'A mint source often evaluated where cooling character matters.',uses:['Flavours & fragrances','Oral care'],review:'Confirm identity, menthol range and applicable grades.'},
 {slug:'spearmint-oil',name:'Spearmint oil',latin:'Mentha spicata',family:'Natural oils',note:'A sweeter mint direction for formulation trials.',uses:['Flavours & fragrances','Confectionery','Oral care'],review:'Confirm botanical identity, carvone profile and grades.'},
 {slug:'dementholised-oil',name:'Dementholised oil',latin:'Mint-derived oil',family:'Rectified & isolated',note:'A processed mint material to assess against a precise brief.',uses:['Flavours & fragrances','Oral care'],review:'Confirm source species, process and exact SKU naming.'},
 {slug:'menthol-crystals',name:'Natural menthol crystals',latin:'Mint-derived menthol',family:'Rectified & isolated',note:'Crystalline menthol for applications requiring defined cooling.',uses:['Confectionery','Pharmaceuticals','Oral care'],review:'Confirm natural status, assay, grade and regulatory route.'},
];
export const segments = [
 {slug:'flavours-fragrances',name:'Flavours & fragrances',line:'Shape the mint note around your sensory target.',body:'Explore source oils and isolated materials with the flavourist or perfumer, then compare samples and analytical data against the intended formula.',need:'Sensory profile, GC data, repeatability and change control.',products:['peppermint-oil','spearmint-oil','cornmint-oil']},
 {slug:'confectionery',name:'Confectionery',line:'Freshness that works in the finished recipe.',body:'For gum, mints and sweets, the right material is the one that survives formulation trials and satisfies food qualification.',need:'Food-use evidence, profile, contaminant data and continuity.',products:['peppermint-oil','spearmint-oil','menthol-crystals']},
 {slug:'pharmaceuticals',name:'Pharmaceuticals',line:'Start with the monograph and the dossier.',body:'Pharmaceutical opportunities require exact grade confirmation, documentation and a formal supplier approval path before supply discussions advance.',need:'Compendial conformity, QA records and regulatory review where applicable.',products:['menthol-crystals','peppermint-oil']},
 {slug:'oral-care',name:'Oral care',line:'Build a precise sensation of freshness.',body:'Evaluate oils and menthol for cooling, taste and stability in toothpaste or mouthwash formulations.',need:'Identity, INCI or relevant declarations, sensory and safety data.',products:['peppermint-oil','spearmint-oil','menthol-crystals']},
 {slug:'distributors',name:'Ingredient distributors',line:'A focused range with the evidence to represent it.',body:'Discuss territory, applications, documentation, replenishment and sample handling before setting a channel agreement.',need:'Complete dossier, clear commercial terms and predictable supply.',products:['peppermint-oil','cornmint-oil','menthol-crystals']},
];
